version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/demo
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /home/ec2-user/demo/scripts/build
      timeout: 60
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/demo/scripts/start
      timeout: 60
      runas: root